# This is a basic workflow to help you get started with Actions

name: trigger-code-glue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TOKEN_ACTIONS: ${{ secrets.TOKEN_ACTIONS}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout code with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Trigger workflow infra
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}

        run: |
          if echo ${ALL_CHANGED_FILES} | grep -q ".github/workflows/main.yml"; then 
            echo "El archivo .github/workflows/main.yml ha sido modificado. No debe ser parte de este proceso."
            exit 1
          else
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $TOKEN_ACTIONS" \
            https://api.github.com/repos/DemoNubiral/MX216822-3-claro-cenam-infre-glue/dispatches \
            -d '{"event_type":"trigger-code", "client_payload": { "changed_files": ${ALL_CHANGED_FILES} }}'
          fi
          
