# This is a basic workflow to help you get started with Actions

name: trigger-code-glue

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:   
      - dev
      - main
    paths:
      - 'process-glue/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TOKEN_ACTIONS: ${{ secrets.TOKEN_ACTIONS}}
  REGION:        ${{ var.REGION }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: prod
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }} 

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.10'

      - name: Install Python requests
        run: pip install requests 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Validate extension file
        id: changed-files-specific
        uses: tj-actions/changed-files@v45
        with:
          files: |
            *.env
            *.py

      - name: Get info data
        run: |
          mkdir file-process
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            cp -r $file file-process
          done 
      
      - name: Validate folders
        id: validate-folder
        run: |
          for file in $(ls file-process); do
            ls -la "file-process/$file"
          done

      - name: Generate Token
        id: generate_token
        run: |
          python - << EOF
          import secrets
          token = secrets.token_hex(5)
          EOF  

      - name: Trigger workflow infra
        env:
            ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}

        run: |
          if echo ${ALL_CHANGED_FILES} | grep -q ".github/workflows/main.yml"; then 
            echo "El archivo .github/workflows/main.yml ha sido modificado. No debe ser parte de este proceso."
            exit 1
          else
            curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $TOKEN_ACTIONS" \
            https://api.github.com/repos/DemoNubiral/MX216822-3-claro-cenam-infre-glue/dispatches \
            -d '{"event_type":"trigger-code", "ISSUE_NUMBER": "${{ steps.create-issue.outputs.ISSUE_NUMBER }}"}'
            -T files-folder.tar.gz
          fi
          
